# Linear Algerbra Part 2
Looking further into Linear Algebra we got left with the following topics and we will cover them here in this notebook.


1. Matrix decomposition
2. SVD
3. Diagonalization
4. EVD

### Matrix Decompostion
Matrix Decomposition or Matrix Factorization, is a fundamental concept in linear algebra.
- Matrix decomposition is a way of reducing a matrix into its fundamental components(simpler decomposed matrices).
- It simplifies complex matrix operations by allowing us to perform calculations on the decomposed matrix rather than the original matrix itself.
- Many machine learning algorithms involve matrix operations, such as solving linear systems of equations, calculating inverses, and determining determinants.
- Matrix decomposition provides a foundation for these operations, making them more efficient and numerically stable.

**Matrix Decompostion Techniques**:
- *LU (Lower-Upper) Decomposition*: Decomposes a square matrix into lower and upper triangular matrices.
- *QR Decomposition*: Factorizes a matrix into an orthogonal matrix (Q) and an upper triangular matrix R.
- *Eigenvalue Decomposition (EVD)*: Decomposes a matrix into eigenvectors and eigenvalues.
- S*ingular Value Decomposition (SVD)*: Breaks down a matrix into three matrices: U, Σ (diagonal matrix), and Vᵀ.

Here in this notebook we look into EVD and SVD of Matrix decomposition techniques.

### Eigen Value Decomposition (EVD)
Eigen Value Decomposition(EVD) is similar to that of Diagonalization.
- EVD is a factorization technique which expresses a square matrix **A** in terms of its eigenvalues and eigenvectors.
- For a matrix **A** , EVD represnts or factorizes as **A = VΛV<sup>-1</sup>**.
- **V** contains teh eigenvectors of **A**.
- **Λ** is the diagonal matrix with eigenvalues of **A**.
- EVD is applicable to any square matrix, whether or not it is symmetric.
- **EVD is used in techniques like Principal Component Analysis (PCA) for dimensionality reduction and solving linear systems of equations.**

In [16]:
import numpy as np

A = np.array([[4, 2], [-5, -3]]) 

# Find eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
V = eigenvectors # eigenvectors of A.

# Create diagonal matrix D having eigenvalues of A as diagonal elements
Lambda = np.diag(eigenvalues)

# Find the inverse of eigenvector matrix V
Vinv = np.linalg.inv(V)

# Perfrom EVD to the matrix A. evd_matrix(Λ) = V_inv*A*V
evd_matrix = np.dot(np.dot(Vinv, A), V)
print("EVD matrix:")
print(evd_matrix)

# confirm that A is corresponding to evd_matrix. A = V*Λ*V_inv.
A_evd = np.dot(V, np.dot(Lambda, Vinv))
print("A_evd natrix:")
print(A_evd)

EVD matrix:
[[ 2.00000000e+00  2.33636299e-16]
 [ 2.26818301e-17 -1.00000000e+00]]
A_evd natrix:
[[ 4.  2.]
 [-5. -3.]]


### Diagonalization

What is Diagonalization any way.  
Firstly lets see what is a Diagonal matrix is?  

**Diagonal Matrix** : It is a square matrix **D** which has its entire non-diagonal elements as zeroes.
- The diagonal matrix only has diagonal elements.
- They allow fast computation of determinants, powers, and inverses of a matrix.
- The determinant of a diagonal matrix is the product of all its diagonal elements.
- A matrix **D<sup>k</sup>** is given by all of its diagonal elements raised to the power of k.
- The inverse of a diagonal matrix is given by **D<sup>-1</sup>** is the reciprocal of all of its elements if all of them are non-zero.

Here we will look into how to tranform a matrix **A** into diagonal form for computational efficiency.

**Diagonalization** :  
- Matrix **A** is diagonalizable if it can be represented in the form of **A = PDP<sup>-1</sup>**.
- **P** is a matrix whose columns are linearly independent eigenvectors of **A**.
- **D** is a diagonal matrix with eigenvalues of **A** on its diagonal.
- Diagonalization is possible only when **A** has a complete set of linearly independent eigenvectors.
- Diagonalization is a specific case of EVD for diagonalizable matrices.
- Symmetric matrices are always diagonalizable, while non-symmetric matrices may or may not be diagonalizable.
- **Diagonalization is used for understanding linear transformations, solving systems of equations.**

Both EVD and Diagonalization has same way of implementing but the difference comes when the matrix is about diagonalizable or not, Symmetric or not and the eigenvectors of the matrix are linearly independent or not. So considering these conditions we can perform appropriate transformations.

In [13]:
# Define the matrix A (2x2 example)
A = np.array([[20, 10],
              [10, 30]])

# Find eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

P = eigenvectors # Linearly independent eigenvectors of A.

# Create diagonal matrix D having eigenvalues of A as diagonal elements
D = np.diag(eigenvalues)

# Find the inverse of eigenvector matrix P
P_inv = np.linalg.inv(P)

# Diagonalize the matrix : D = P_inv*A*P 
diagonalized_matrix = np.dot(np.dot(P_inv, A), P)

print("Diagonalized Matrix:")
print(diagonalized_matrix)

# A = P*D*P_inv  confirm that the diagonalized form of matrix A is D(diagonalized_matrix).
A_diag = np.dot(np.dot(P, diagonalized_matrix), P_inv)
print("A_diag:")
print(A_diag)

Diagonalized Matrix:
[[ 1.38196601e+01 -3.84003946e-16]
 [ 4.77991462e-15  3.61803399e+01]]
A_diag:
[[20. 10.]
 [10. 30.]]


### Singular Value Decomposition (SVD)
SVD is the central matrix decompostion method in linear algebra. 
- SVD factorizes the matrix **A** into three matrices **U, Σ, V<sup>T</sup>**.
- For a matrix A of size **m**x**n** the vectors **U, Σ, V** are:
- **U**: An **m**x**m** matrix containing orthonormal eigenvectors of **AA<sup>T</sup>**.
- **Σ**: A diagonal matrix with singular values (positive square roots of eigenvalues of **AA<sup>T</sup>** or **A<sup>T</sup>A**).
- **Vᵀ**: The transpose of an **m**x**m** matrix containing orthonormal eigenvectors of **A<sup>T</sup>A**.
- **SVD has various applications like Dimensionality Reduction, Pseudo-inverse, Noise Reduciton and Image compression etc.**

**A = UΣV<sup>T</sup>**


In [20]:
# matrix A
A = np.array([[4, 0],
              [0, 3]])

# Compute the SVD numpy has the function np.linalg.svd() function to get svd matrices.
U, Sigma, Vt = np.linalg.svd(A)

print("Matrix A:")
print(A)
print("\nU matrix:")
print(U)
print("\nSigma matrix (as a diagonal matrix):")
print(np.diag(Sigma))
print("\nVt matrix:")
print(Vt)

# confirm that A = UΣV_t
A_svd = np.dot(np.dot(U, np.diag(Sigma)), Vt)
print("\nA_svd matrix:")
print(A_svd)

Matrix A:
[[4 0]
 [0 3]]

U matrix:
[[1. 0.]
 [0. 1.]]

Sigma matrix (as a diagonal matrix):
[[4. 0.]
 [0. 3.]]

Vt matrix:
[[1. 0.]
 [0. 1.]]

A_svd matrix:
[[4. 0.]
 [0. 3.]]


### Tensor

Tensor is a mathematical object in an m-dimensional space of rank of n which has n indices, m<sup>n</sup> components while obeying certain transformation rules.

In short a 0-dimensional Tensor is a scalar, 1-dimensional Tensor is a vector and 2-dimensional Tensor is a matrix and so on.,
- The most important point to remember is that Tensors are dymnamic. Thats what it makes differ from a matrix.
- Tensors will transform when interacting with other mathematical entities, matrices don't always have this property.
- Refer to this wonderful article from **Steven Steinke** about fundamental differnece between <a href = 'https://medium.com/@quantumsteinke/whats-the-difference-between-a-matrix-and-a-tensor-4505fbdc576c'>matrices and Tensor</a>.
- We can create tensors from both tensorflow and PyTorch libraries of python. Official documentation will be helpful to you to understand it better. No difference will you find if yu already know about linear algebra, matrices.
- <a href='https://www.tensorflow.org/guide/tensor'>Tensorflow tensors</a> , <a href='https://pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html'>PyTorch tensors</a>


We will point out what are the uses of Tensors and why they have choosen over matrices in DeepLearning networks.
- Tensors can play an important role in ML by encoding multi-dimensional data. 
- Can develop more robust models in DeepLearning than using matrices.
- DeepLearning involves in computing hundreds of thousands of dimensions and fields. Tensors can store data in any no of N dimensoins.

### Conclusion

The topics covered in Linear Algebra are crucial for machine learning applications. More advanced topics are omitted here, as they serve specific purposes for particular algorithms or techniques. Learning algorithms in machine learning may involve selecting specific advanced topics. The discussed applications include data representation, manipulation, dimensionality reduction, solving linear equations, and image compression, highlighting the significance of Linear Algebra in machine learning.

To delve deeper into Linear Algebra for machine learning, consider exploring topics such as Pseudo-Inverse calculation and applications like Dimensionality Reduction Techniques. The aforementioned topics provide a comprehensive understanding of Linear Algebra's role in machine learning. For additional learning resources, refer to the readme file.

As of now stated there are many applications of Linear Algebra in machine learning, simply it is the heart of Machine Learning. Those applications drive the foremost importance of learning Linear Algebra while diving into Machine Learning. Further topics we will cover are probability, calculus, and statistics have almost equal significance in machine learning.