# Linear Algerbra Part 1  
At first we are going to cover basics of linear algebra, which is a great way to begin because of its importance.

In mathematics Linear algebra is the study of vectors and certain rules to manipulate vectors. It plays crucial role in Machine Learning and also it is said that Linear algebra lies at the heart of DeepLearning. Having a detailed explanation of theory and implementing the concepts learnt with some examples, we will understand and gain knowledge on how does Linear algebra helps the complex models solve equations in multidimensional space and to find the underlying patterns of data.  

**At the end of this topic you will be able to :**
- Understand the basics of Linear algebra.
- Learn how to use numpy library to implement the operations in vector and matrix algebra
- Know how the underlying equations in machine learning models work.

**Resources :**  
- 📕 Given already the link to Mathematics for ML book in the main page refer it for better insights.
- 🎬["M4ML- Linear algebra by ImperialCollege"](https://www.youtube.com/playlist?list=PLiiljHvN6z1_o1ztXTKWPrShrMrBLo5P3)  this YouTube playlist also helps a lot for better understanding.

## Topics we cover here..
1. [Vectors, scalars operations](#vectors-and-scalars)
2. [Projection](#projection)
3. [Orthogonal and Orthonormal](#orthogonal-and-orthonormal-vectors)
4. [Matrices properties and operations](#matrices-and-operations)
5. [System of Linear equations](#system-of-linear-equations)   
6. [Norms](#norms)
7. [Eigen values and Eigen vectors](#eigen-values-and-eigen-vectors) 
9. [Vector spaces and sub spaces](#vector-spaces-and-sub-spaces)


### Vectors and Scalars
Vector : Vectors are used to represent quantities that have both a size (magnitude) and a direction, such as displacement, velocity, force, and many other physical quantities. vectors with magnitude and direction can be used to represent various types of data, features, and parameters.
 
Scaler : A scalar is a single numerical value that represents a quantity with magnitude only (no direction).

Looking into vectors.

**Representation and Operations**  
Vector is actually created using ***'numpy.array()'*** method which takes a list of scalars as argument and return a ***'nump.ndarray'*** vector object.  
We can perform Addition, Subraction, Multiplication of vectors with a scalar and with an another vector. We cannot divide a vector with an another vector but we can divide it with a scalar.  
Addition, subraction, division and Multiplication between vectors must need same size of vectors. 
Division of a vector by another vector not possible at all.

In [1]:
# numpy the library for performaing operations among vectors and matrices
# we use import keyword to 'import' any library or package and 'as' to name an alias to the original imported package 
import numpy as np 

In [2]:
# vector is basically a list or array but we use numpy to represent those arrays we can also represent it by lists.
# the reason is that numpy is written in C and C++ which makes it much faster while operating large vectors or datasets  

vector_1 = np.array([10, 11, 12, 13, 14]) # this is how you define an array in numpy called 'numpy array'
vector_2 = np.array([1, 2, 4, 5, 8])

print(type(vector_1)) # the type of vector_1 is 'numpy.ndarray'

<class 'numpy.ndarray'>


Addition : This operation increases the magnitude of the vector while maintaining its direction.  
Subraction : This operation decreases the magnitude of the vector while maintaining its direction.  
Multiplication : Scaling the vector, which affects its magnitude and, potentially, its direction.
- If c is positive, the direction of the vector remains the same.
- If c is negative, the direction of the vector is reversed.  

Dividing : This is not a standard operationin algebra.

In [3]:
# adding two vectors simply gives the sum of each corresponding elements in the vectors.

vector_sum = vector_1 + vector_2
print(vector_sum) # gives the sum of individual elements in the vectors
# subracting does the same

[11 13 16 18 22]


In [4]:
# multiplying the vectors with a scalar and Dividing vector with a scalar.
# when vector is multiplied by a scalar or vice versa it yields new vector of same shape with all the elements multiplied with the scalar
# when vector divided by a scalar it yields new vector of same shape with all the elements divided by scalar.
# when scalar divided by a vector it yields new vector of same shape with scalar is divided by all the corresponding elements of vector.


vector_mul_scalar = vector_2 * 2 # same with '2 * vector_2' doubles the magnitude
print("scalar multipled: " ,vector_mul_scalar) # result vector all elements are multiplied by the scalar 2

vector_div = vector_2 / 10 # all elements divided by the scalar
print("divided by scalar: ", vector_div)

vector_div = 10 / vector_2 # scalar 10 is divided by all the corresponding elements
print("scalar divided by vector: ",vector_div)

scalar multipled:  [ 2  4  8 10 16]
divided by scalar:  [0.1 0.2 0.4 0.5 0.8]
scalar divided by vector:  [10.    5.    2.5   2.    1.25]


**Dot Product :**  
- The dot product takes two equal-lengthed vectors, multiply corresponding elements and add the products then returns a single scalar.  
- Dot product between two vectors result in a scalar value.
- Geometrically it is product of magnitude of a, b, and cosine of angle between them **A . B = |A| * |B| \* cos(θ)**.
- It is used in vector projection to find the component of one vector in the direction of another.
- dot product annotaed like **A . B, A<sup>T</sup>B**

**Cross Product :**  
- The cross product is a binary operation on two vectors in 3D space. Cross product can only be done on 3D vectors and not Matrices.  
- In three-dimensional space, vectors can be used to represent directed line segments, and the cross product provides a way to calculate a vector that is perpendicular to the plane containing the original vectors.  
- Geometrically it is product of magnitude of a, b, and cosine of angle between them the resultant scalar multiplied by a unit vector in the direction perpendicular to both A and B **A x B = (|A| * |B| \* sin(θ)) \* n**. 

You can find the implementation of the cross product in below image.
<center><img src="images/CrossProduct.png" width="350" height="220" align="center"/></center>

***Vector multiplilcation*** is done by either dot product or cross product based on our use. We can use ***np.dot()*** or ***np.multiply()*** or ***np.matmul()***.
-  dot products are between vectors only.
- np.dot() and np.matmul() perform necessary multiplication but np.multiply() just multiply the corresponding elements

In [5]:
# Using np.dot() 
result_dot_vector = np.dot(vector_1, vector_2)
# Using np.matmul() 
result_matmul_vector = np.matmul(vector_1, vector_2)
# Using np.multiply() 
result_multiply_vector = np.multiply(vector_1, vector_2)

print(vector_1, " " ,vector_2)
print("Dot Product :",result_dot_vector)
print("matmul :",result_matmul_vector)
print("multiply:",result_multiply_vector)


[10 11 12 13 14]   [1 2 4 5 8]
Dot Product : 257
matmul : 257
multiply: [ 10  22  48  65 112]


### Projection
The projection of a vector onto another vector is a fundamental operation that represents the "shadow" of one vector onto the other.  
The projection of vector A onto vector B is the vector component of A that lies in the direction of B.  

Below shown the formula for projection of vector A onto vector v.
<center><img src="images/Projection.png" width="300" height="100" align="center"/></center>



### Orthogonal and Orthonormal vectors

***Orthogonal vectors*** :   
Two vectors are orthogonal if their dot product is zero. Mathematically, vectors A and B are orthogonal if  **A ⋅ B = 0**. Geometrically, orthogonal vectors are perpendicular to each other in n-dimensional space.  
Orthogonal vectors do not have any component in the direction of each other. They form a right angle, and the cosine of the angle between them is zero. 

***Orthonormal vectors*** :  
A set of vectors is orthonormal if all vectors are orthogonal to each other and have unit length. let **A<sub>1</sub>, A<sub>2</sub> . . . A<sub>n</sub>** be set of Vectors are orthonormal if :  
**A<sub>i</sub> . A<sub>j</sub> = 0,   i != j**  
**A<sub>i</sub> = 1,  for all i**

### Matrices and Operations

Matrix : An ordered set of numbers arranged in two dimensions, forming rows and columns. Each element in a matrix is identified by two indices, one for the row and one for the column. A 2D matrix indeed contains multiple 1D vectors, where each row or column can be considered a 1D vector.   
In ML we often represent datasets(data) in the form of matrices, and many ML algorithms involved in computation of Matrix operations. More advanced concepts in matrices also has specific uses in the advanced ML algorithms which will be covered further. 

Matrix operations like addition and subtraction are similar to the vectors where adding corresponding elements in both matrices. Similarly there exists no matrix to matrix division. And matrix to matrix multiplication is done using cross product which yields a new matrix. we can do it using both ***np.dot()*** and ***np.matmul()***.

In [6]:
matrix_A = np.array([[1, 2, 3], [1, 1, 1], [1, 2, 4]])
matrix_B = np.array([[2, 3, 4], [1, 2, 1], [2, 2, 1]])

matrix_dot = np.dot(matrix_A, matrix_B)
matrix_mul = np.matmul(matrix_A, matrix_B)

print("using dot: \n", matrix_dot)
print("usng matmul: \n",matrix_mul)

using dot: 
 [[10 13  9]
 [ 5  7  6]
 [12 15 10]]
usng matmul: 
 [[10 13  9]
 [ 5  7  6]
 [12 15 10]]


#### Transpose of a matrix
The transpose of a matrix is found by interchanging its rows into columns or columns into rows. 

In [7]:
T = np.array([[1, 2, 3], [3, 4, 5], [5, 6, 7]])
print(T)
print("Transpose: \n",T.transpose())

[[1 2 3]
 [3 4 5]
 [5 6 7]]
Transpose: 
 [[1 3 5]
 [2 4 6]
 [3 5 7]]


#### Identity Matrix
Square Matrix having only diagonal elements value of 1 all other 0's.

In [8]:
I = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
print(I)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### Symmetric Matrix
Matrix which is equal to its Transpose



In [9]:
S = np.array([[2, 3, 6], [3, 4, 5], [6, 5, 9]])
print(S)
print("Symmetric Matrix: \n",S.transpose())

[[2 3 6]
 [3 4 5]
 [6 5 9]]
Symmetric Matrix: 
 [[2 3 6]
 [3 4 5]
 [6 5 9]]


#### Trace of a matrix 
The sum of the diagonal elements in a matrix.

In [10]:
S = np.array([[2, 3, 6], [3, 4, 5], [6, 5, 9]])
print(S)
print("Trace of Matrix: ",S.trace())

[[2 3 6]
 [3 4 5]
 [6 5 9]]
Trace of Matrix:  15


#### Determinant of a matrix

The determinant of a square matrix is a scalar value that can be computed from its elements. The determinant is a measure of the "scaling factor" of the linear transformation represented by the matrix.  
Determinant only exists for a square matrix and also inverse .


In [11]:
S = np.array([[2, 3, 3], [3, 4, 5], [6, 5, 1]])
print("determinant of S: ",np.linalg.det(S))

determinant of S:  12.0


#### Inverse of a Matrix

- We denote its inverse as **A<sup>-1</sup>**. The inverse of a matrix is another matrix that, when multiplied by the given matrix, yields the multiplicative identity.   
- For a matrix **A**, its inverse is **A<sup>-1</sup>**. And **A . A<sup>-1</sup> = I**, where **I** is denoted as the identity matrix.  
- Same as determinant Inverse of a matrix only exists for a square matrix and a non singular matrix, which means a matrix having a non zero determinant.  
- The inverse of a matrix is the adjoint matrix of **A** multiplied by inverse of determinant of **A**.  
- The adjoint of a matrix, also called the adjugate of a matrix, is defined as the transpose of the cofactor matrix of that particular matrix. For a matrix A, the adjoint is denoted as adj (A).  
- Inverse of matrix has some important useful in complex calculations. For example in Linear regression.

Formula for Inverse of a matrix is denoted below:

<center><img src="images/inverse.webp" width="300" height="100" align="center"/></center>


In [12]:
S = np.array([[2, 1, 1], [1, 3, 2], [1, 0, 0]])
inv_S = np.linalg.inv(S)

print("Inverse of S:\n",inv_S)

result = np.dot(S, inv_S)
print("result Identity matrix:\n", result)

Inverse of S:
 [[ 0.  0.  1.]
 [-2.  1.  3.]
 [ 3. -1. -5.]]
result Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Rank of a Matrix  
The maximum number of linearly independent columns (or rows) of a matrix is called the rank of a matrix.  
The rank of a matrix cannot exceed the number of its rows or columns.  
If we consider a square matrix, the columns (rows) are linearly independent only if the matrix is nonsingular.

In [13]:
R = np.array([[2, 1, 1], [1, 3, 2], [1, 0, 0]])
print("Rank of matrix: ",np.linalg.matrix_rank(R))

Rank of matrix:  3


### System of Linear Equations
- System of linear equations are group of linear equations can be represented in matrix form using a coefficient matrix, a variable matrix, and a constant matrix.   
- They will be represented using an equation **A x = b** where A is the linear equation(coefficient) matrix, x is variable matrix and b is constant matrix.  

**Solving the linear equations**:   
- We can solve the linear equations by elimination or substitution methods. We can explore the method of using rank.
- Given the linear system **Ax = B** and the augmented matrix **(A|B)**.  
- Augmented matrix is just adding the constant matrix **b** as the column vector to matrix **A**.   
1. If rank(A) = rank(A|B) = the number of rows in x(variables), then the system has a unique solution.   
2. If rank(A) = rank(A|B) < the number of rows in x(variables), then the system has infintely many solutions.  
3. If rank(A) < rank(A|B), then the system is inconsistent.


Below shown how actually the two linear equations will be represented as per the formula..  
**2 - x = 0**  
**-x + y = 3**
<center><img src="images/SystemOfEq.webp" width="300" height="170" align="center"/></center>

In [14]:
# Coefficient matrix
A = np.array([[2, -1], [-1, 2]])

# Right-hand side vector
B = np.array([0, 3])

# Augmented matrix [A|B]
AB = np.column_stack((A, B))

# Find the ranks
rank_A = np.linalg.matrix_rank(A)
rank_AB = np.linalg.matrix_rank(AB)

#satisfies the condition of  rank(A) = rank(A|B) = the number of rows in x(variables) hence has unique solution
print("Rank of A:", rank_A)
print("Rank of [A|B]:", rank_AB)

#solution
solution = np.linalg.solve(A,B) 
# we use np.linalg.solve() method to solve the linear equations 
# but it throws error when the equations have either no solution or infinitely many solution.

print("Solution for Ax=B: ", solution)


Rank of A: 2
Rank of [A|B]: 2
Solution for Ax=B:  [1. 2.]


### Norms
- In mathematics, a norm is a function that assigns a positive real number to each vector in a vector space.   
- Norms are used to measure the size or length of vectors and are a generalization of the concept of absolute value in one-dimensional spaces
- Mainly discuss about two Norms here L1(Manhattan / Taxicab) Norm, L2(Euclidean) Norm.

**L1 or Manhattan norm**:  
- Manhattan distance the sum of the absolute differences between the coordinates.
- **distance = |x1 - x2| + |y1 - y2|**

**L2 or Euclidean norm**:  
- Euclidean distance the square root of sum of squared differnces of coordinates.
- Its the basic distance formula between two points.

In [15]:
import numpy as np

# Manhattan Distance (L1-norm)
P = np.array([2, 3])
Q = np.array([5, 7])

# why Q - P is its  the basic operation of finding the distance between two points
# the expression Q−P represents the vector pointing from point P to point Q. 
# The resulting vector provides the direction and magnitude needed to go from P to Q.

manhattan_distance = np.linalg.norm(Q - P, ord=1)

# Euclidean Distance (L2-norm)
euclidean_distance = np.linalg.norm(Q - P, ord=2)

print("Manhattan Distance:", manhattan_distance)
print("Euclidean Distance:", euclidean_distance)


Manhattan Distance: 7.0
Euclidean Distance: 5.0


### Eigen values and Eigen vectors

- Linear transformations of a vector is scaling, rotating and shearing of the vector and transforming it into a new form.
- They are mathematical operations that alter the shape, orientation, or position of vectors while preserving certain properties 
<br></br>
- Eigen vectors are those vectors which lie along the same span in both before and after a Linear transformation to a space.
- Eigen values are the amount of each of those eigen vectors has streched or shrinked.
- Eigen vectors and eigen values are most useful in PCA, Image and Signal processings.
<br></br>
- For a square matrix **A**, a scalar **λ** is considered an eigenvalue if there exists a non-zero vector **v** (eigenvector) such that **Av = λv**.
-  A non-zero vector **v** is an eigenvector of a square matrix **A** if **Av = λv**, where **λ** is the corresponding eigenvalue.

Below shown the formula : 
<center><img src="images/EigenValues_and_Vectors.png" width="300" height="220" align="center"/></center>


In [16]:
# 3x3 matrix
A = np.array([[1, 2, 1],
              [6, -1, 0],
              [-1, -2, -1]])

# Find eigenvalues and eigenvectors
# function 'numpy.linalg.eig()' will return the eigenvalues and eigenvectors of the matrix A.
eigenvalues_B, eigenvectors_B = np.linalg.eig(A)

print("Matrix A:")
print(A)
print("\nEigenvalues:")
print(eigenvalues_B)
print("\nEigenvectors:")
print(eigenvectors_B)


Matrix A:
[[ 1  2  1]
 [ 6 -1  0]
 [-1 -2 -1]]

Eigenvalues:
[-4.00000000e+00  3.00000000e+00  1.59494787e-16]

Eigenvectors:
[[ 0.40824829 -0.48507125 -0.0696733 ]
 [-0.81649658 -0.72760688 -0.41803981]
 [-0.40824829  0.48507125  0.90575292]]


### Vector Spaces and Sub Spaces

- If **n** is a positive integer, then an ordered n-tuple is a sequence of **n** real numbers (**a<sub>1</sub>, a<sub>2</sub>, . . . , a<sub>n</sub>)**.  
- The set of all ordered n-tuples is called n-space and is denoted by R<sup>n</sup>.
<br></br>
- If **n = 1** then all the tuples have exactly one real number then **R** will be the set of real numbers.
- The vector space **R<sup>3</sup>**, is the set of ordered triples, which describe all points and directed line segments in 3D space.
- You can term those triples as 3D point or a vector.
<br></br>
- A vector space **V** over a field **F** is a nonempty set on which two operations are defined - addition and scalar multiplication.
- Say objects **u** and **v** in space **V** and scalar **k** belongs **F** . They should satisfy the following axioms.

1. If **u**, **v ∈ V** , then **u + v ∈ V** .
2. If **u ∈ V** and **k ∈ F**, then **ku ∈ V** .
3. **u + v = v + u**
4. **u + (v + w) = (u + v) + w**
5. There is an object 0 in **V**, called a zero vector for **V** , such that **u + 0 = 0 + u = u** for all **u** in **V** .
6. For each **u** in **V** , there is an object **-u** in **V** , called the additive inverse of **u**,such that **u + (−u) = −u + u = 0**
7. And associative rule, commutative rule.
<br></br>
- A subset **W** of a vector space **V** is called a subspace of **V** if **W** is itself a vector space under the addition and scalar multiplication defined on **V**.
- That is simply satisfying all the axioms of Vector space.

#### I suggest you to explore **Eigen Vectors, Eigen Values, Vector Spaces and Subspaces** in-depth through additional resources for a comprehensive understanding beyond concise explanations. Because these axioms and statements might not give you a perfect explanation.

<hr></hr>

- #### In the next chapter or module we will look into SVD, EVD, Gradients, Tensors etc..,
#### Like I said refer to some text book whenever you get stuck. 
#### I hope this was helpful, I've given you a high-level understanding of what linear algebra is and how we implement it using python numpy library. I think this level is enough for you to continue your progress. 

- All kinds of suggestions are acceptable please feel free to reach out to me my **LinkedIn [Govardhan V](https://www.linkedin.com/in/govardhan-vembadi/)**